image:
  name: node

stages:
  - test
  - deploy

unit-test-job:
  stage: test
  script:
    - npm i
    - npm run lint
    - npm run coverage

npm-deploy:
  stage: deploy
  script:
    - npm i
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >.npmrc
    - npm publish
  only:
    - release